### ISSUE TITLE
Issues #05: Add ticket business logic

### ISSUE THREAD

**Issue by Dieky** [cph-Pack/SS_OLA2#5]
Description: Create the business logic for handling a driver's ticket.

Acceptance criteria:
- Must create Ticket class that can contain the ticket details; driver's first- and last name, company name, and shipment details, including the chemicals (A, B, or C) and amount in kilo units.

**Comment by CarolineHoeg** [comment]
Ticket's shipment details bør også indeholde om det er en delivery eller collection, for det skal Job kende til, men job kender kun ticket.
