### ISSUE TITLE
Issues #09: Add ticket validation endpoint

### ISSUE THREAD

**Issue by CarolineHoeg** [cph-Pack/SS_OLA2#9]
Description: Create the endpoint which allows for validation of a driver's ticket by verifying the driver’s details, company name, and chemical shipment details.

Acceptance criteria:
- The ticket must be in json format and contain driver first- and last name, company name, and shipment details, including the chemicals (A, B, or C) and amount in kilo units.
- Must respond with useful message and status code - 200 (OK) or 400 (Bad Request)

User acceptance criteria:
Given a driver arrives at the gate with a ticket,
When the gate staff enter or scan the ticket details into the system,
Then the system should check the driver’s name, company, and chemical
shipment details against the ticket. 

Given the ticket details are incorrect,
When the validation is performed,
Then the system should display an error message to the gate staff.

Given the ticket details are correct,
When the validation is performed,
Then the system should allow the gate staff to proceed with job creation.

**Comment by Dieky** [comment]
@Keveren1 HEJ KEVIN

**Comment by Keveren1** [comment]
@Dieky GODDAG :)
